// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.1.0.
// **********************************************************************

#ifndef __PATCH_H_
#define __PATCH_H_

#include <map>
#include <string>
#include <vector>
#include "tup/Tars.h"
#include "tup/TarsJson.h"
using namespace std;
#include "servant/ServantProxy.h"
#include "servant/Servant.h"
#include "promise/promise.h"


namespace tars
{
    struct FileInfo : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "tars.FileInfo";
        }
        static string MD5()
        {
            return "6c7679ddfd0048dbd9c8d8084bfd53c0";
        }
        FileInfo()
        :path(""),size(0),canExec(true),md5("")
        {
        }
        void resetDefautlt()
        {
            path = "";
            size = 0;
            canExec = true;
            md5 = "";
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(path, 0);
            _os.write(size, 1);
            _os.write(canExec, 2);
            if (md5 != "")
            {
                _os.write(md5, 3);
            }
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(path, 0, true);
            _is.read(size, 1, true);
            _is.read(canExec, 2, true);
            _is.read(md5, 3, false);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["path"] = tars::JsonOutput::writeJson(path);
            p->value["size"] = tars::JsonOutput::writeJson(size);
            p->value["canExec"] = tars::JsonOutput::writeJson(canExec);
            if (md5 != "")
            {
                p->value["md5"] = tars::JsonOutput::writeJson(md5);
            }
            return p;
        }
        string writeToJsonString()
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(path,pObj->value["path"], true);
            tars::JsonInput::readJson(size,pObj->value["size"], true);
            tars::JsonInput::readJson(canExec,pObj->value["canExec"], true);
            tars::JsonInput::readJson(md5,pObj->value["md5"], false);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(path,"path");
            _ds.display(size,"size");
            _ds.display(canExec,"canExec");
            _ds.display(md5,"md5");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(path, true);
            _ds.displaySimple(size, true);
            _ds.displaySimple(canExec, true);
            _ds.displaySimple(md5, false);
            return _os;
        }
    public:
        std::string path;
        tars::Int32 size;
        tars::Bool canExec;
        std::string md5;
    };
    inline bool operator==(const FileInfo&l, const FileInfo&r)
    {
        return l.path == r.path && l.size == r.size && l.canExec == r.canExec && l.md5 == r.md5;
    }
    inline bool operator!=(const FileInfo&l, const FileInfo&r)
    {
        return !(l == r);
    }


    /* callback of async proxy for client */
    class PatchPrxCallback: public tars::ServantProxyCallback
    {
    public:
        virtual ~PatchPrxCallback(){}
        virtual void callback_download(tars::Int32 ret,  const vector<tars::Char>& vb)
        { throw std::runtime_error("callback_download() override incorrect."); }
        virtual void callback_download_exception(tars::Int32 ret)
        { throw std::runtime_error("callback_download_exception() override incorrect."); }

        virtual void callback_listFileInfo(tars::Int32 ret,  const vector<tars::FileInfo>& vf)
        { throw std::runtime_error("callback_listFileInfo() override incorrect."); }
        virtual void callback_listFileInfo_exception(tars::Int32 ret)
        { throw std::runtime_error("callback_listFileInfo_exception() override incorrect."); }

        virtual void callback_preparePatchFile(tars::Int32 ret)
        { throw std::runtime_error("callback_preparePatchFile() override incorrect."); }
        virtual void callback_preparePatchFile_exception(tars::Int32 ret)
        { throw std::runtime_error("callback_preparePatchFile_exception() override incorrect."); }

    public:
        virtual const map<std::string, std::string> & getResponseContext() const
        {
            CallbackThreadData * pCbtd = CallbackThreadData::getData();
            assert(pCbtd != NULL);

            if(!pCbtd->getContextValid())
            {
                throw TC_Exception("cann't get response context");
            }
            return pCbtd->getResponseContext();
        }

    public:
        virtual int onDispatch(tars::ReqMessagePtr msg)
        {
            static ::std::string __Patch_all[]=
            {
                "download",
                "listFileInfo",
                "preparePatchFile"
            };
            pair<string*, string*> r = equal_range(__Patch_all, __Patch_all+3, string(msg->request.sFuncName));
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __Patch_all)
            {
                case 0:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_download_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);
                    tars::Int32 _ret;
                    _is.read(_ret, 0, true);

                    vector<tars::Char> vb;
                    _is.read(vb, 3, true);
                    CallbackThreadData * pCbtd = CallbackThreadData::getData();
                    assert(pCbtd != NULL);

                    pCbtd->setResponseContext(msg->response.context);

                    callback_download(_ret, vb);

                    pCbtd->delResponseContext();

                    return tars::TARSSERVERSUCCESS;

                }
                case 1:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_listFileInfo_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);
                    tars::Int32 _ret;
                    _is.read(_ret, 0, true);

                    vector<tars::FileInfo> vf;
                    _is.read(vf, 2, true);
                    CallbackThreadData * pCbtd = CallbackThreadData::getData();
                    assert(pCbtd != NULL);

                    pCbtd->setResponseContext(msg->response.context);

                    callback_listFileInfo(_ret, vf);

                    pCbtd->delResponseContext();

                    return tars::TARSSERVERSUCCESS;

                }
                case 2:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_preparePatchFile_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);
                    tars::Int32 _ret;
                    _is.read(_ret, 0, true);

                    CallbackThreadData * pCbtd = CallbackThreadData::getData();
                    assert(pCbtd != NULL);

                    pCbtd->setResponseContext(msg->response.context);

                    callback_preparePatchFile(_ret);

                    pCbtd->delResponseContext();

                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }

    };
    typedef tars::TC_AutoPtr<PatchPrxCallback> PatchPrxCallbackPtr;

    /* callback of promise async proxy for client */
    class PatchPrxCallbackPromise: public tars::ServantProxyCallback
    {
    public:
        virtual ~PatchPrxCallbackPromise(){}
    public:
        struct Promisedownload: virtual public TC_HandleBase
        {
        public:
            tars::Int32 _ret;
            vector<tars::Char> vb;
            map<std::string, std::string> _mRspContext;
        };
        
        typedef tars::TC_AutoPtr< PatchPrxCallbackPromise::Promisedownload > PromisedownloadPtr;

        PatchPrxCallbackPromise(const promise::Promise< PatchPrxCallbackPromise::PromisedownloadPtr > &promise)
        : _promise_download(promise)
        {}
        
        virtual void callback_download(const PatchPrxCallbackPromise::PromisedownloadPtr &ptr)
        {
            _promise_download.setValue(ptr);
        }
        virtual void callback_download_exception(tars::Int32 ret)
        {
            std::string str("");
            str += "Function:download_exception|Ret:";
            str += TC_Common::tostr(ret);
            _promise_download.setException(promise::copyException(str, ret));
        }

    protected:
        promise::Promise< PatchPrxCallbackPromise::PromisedownloadPtr > _promise_download;

    public:
        struct PromiselistFileInfo: virtual public TC_HandleBase
        {
        public:
            tars::Int32 _ret;
            vector<tars::FileInfo> vf;
            map<std::string, std::string> _mRspContext;
        };
        
        typedef tars::TC_AutoPtr< PatchPrxCallbackPromise::PromiselistFileInfo > PromiselistFileInfoPtr;

        PatchPrxCallbackPromise(const promise::Promise< PatchPrxCallbackPromise::PromiselistFileInfoPtr > &promise)
        : _promise_listFileInfo(promise)
        {}
        
        virtual void callback_listFileInfo(const PatchPrxCallbackPromise::PromiselistFileInfoPtr &ptr)
        {
            _promise_listFileInfo.setValue(ptr);
        }
        virtual void callback_listFileInfo_exception(tars::Int32 ret)
        {
            std::string str("");
            str += "Function:listFileInfo_exception|Ret:";
            str += TC_Common::tostr(ret);
            _promise_listFileInfo.setException(promise::copyException(str, ret));
        }

    protected:
        promise::Promise< PatchPrxCallbackPromise::PromiselistFileInfoPtr > _promise_listFileInfo;

    public:
        struct PromisepreparePatchFile: virtual public TC_HandleBase
        {
        public:
            tars::Int32 _ret;
            map<std::string, std::string> _mRspContext;
        };
        
        typedef tars::TC_AutoPtr< PatchPrxCallbackPromise::PromisepreparePatchFile > PromisepreparePatchFilePtr;

        PatchPrxCallbackPromise(const promise::Promise< PatchPrxCallbackPromise::PromisepreparePatchFilePtr > &promise)
        : _promise_preparePatchFile(promise)
        {}
        
        virtual void callback_preparePatchFile(const PatchPrxCallbackPromise::PromisepreparePatchFilePtr &ptr)
        {
            _promise_preparePatchFile.setValue(ptr);
        }
        virtual void callback_preparePatchFile_exception(tars::Int32 ret)
        {
            std::string str("");
            str += "Function:preparePatchFile_exception|Ret:";
            str += TC_Common::tostr(ret);
            _promise_preparePatchFile.setException(promise::copyException(str, ret));
        }

    protected:
        promise::Promise< PatchPrxCallbackPromise::PromisepreparePatchFilePtr > _promise_preparePatchFile;

    public:
        virtual int onDispatch(tars::ReqMessagePtr msg)
        {
            static ::std::string __Patch_all[]=
            {
                "download",
                "listFileInfo",
                "preparePatchFile"
            };

            pair<string*, string*> r = equal_range(__Patch_all, __Patch_all+3, string(msg->request.sFuncName));
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __Patch_all)
            {
                case 0:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_download_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);

                    PatchPrxCallbackPromise::PromisedownloadPtr ptr = new PatchPrxCallbackPromise::Promisedownload();

                    try
                    {
                        _is.read(ptr->_ret, 0, true);

                        _is.read(ptr->vb, 3, true);
                    }
                    catch(std::exception &ex)
                    {
                        callback_download_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_download_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    ptr->_mRspContext = msg->response.context;

                    callback_download(ptr);

                    return tars::TARSSERVERSUCCESS;

                }
                case 1:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_listFileInfo_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);

                    PatchPrxCallbackPromise::PromiselistFileInfoPtr ptr = new PatchPrxCallbackPromise::PromiselistFileInfo();

                    try
                    {
                        _is.read(ptr->_ret, 0, true);

                        _is.read(ptr->vf, 2, true);
                    }
                    catch(std::exception &ex)
                    {
                        callback_listFileInfo_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_listFileInfo_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    ptr->_mRspContext = msg->response.context;

                    callback_listFileInfo(ptr);

                    return tars::TARSSERVERSUCCESS;

                }
                case 2:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_preparePatchFile_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);

                    PatchPrxCallbackPromise::PromisepreparePatchFilePtr ptr = new PatchPrxCallbackPromise::PromisepreparePatchFile();

                    try
                    {
                        _is.read(ptr->_ret, 0, true);

                    }
                    catch(std::exception &ex)
                    {
                        callback_preparePatchFile_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_preparePatchFile_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    ptr->_mRspContext = msg->response.context;

                    callback_preparePatchFile(ptr);

                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }

    };
    typedef tars::TC_AutoPtr<PatchPrxCallbackPromise> PatchPrxCallbackPromisePtr;

    /* callback of coroutine async proxy for client */
    class PatchCoroPrxCallback: public PatchPrxCallback
    {
    public:
        virtual ~PatchCoroPrxCallback(){}
    public:
        virtual const map<std::string, std::string> & getResponseContext() const { return _mRspContext; }

        virtual void setResponseContext(const map<std::string, std::string> &mContext) { _mRspContext = mContext; }

    public:
        int onDispatch(tars::ReqMessagePtr msg)
        {
            static ::std::string __Patch_all[]=
            {
                "download",
                "listFileInfo",
                "preparePatchFile"
            };

            pair<string*, string*> r = equal_range(__Patch_all, __Patch_all+3, string(msg->request.sFuncName));
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __Patch_all)
            {
                case 0:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_download_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);
                    try
                    {
                        tars::Int32 _ret;
                        _is.read(_ret, 0, true);

                        vector<tars::Char> vb;
                        _is.read(vb, 3, true);
                        setResponseContext(msg->response.context);

                        callback_download(_ret, vb);

                    }
                    catch(std::exception &ex)
                    {
                        callback_download_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_download_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    return tars::TARSSERVERSUCCESS;

                }
                case 1:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_listFileInfo_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);
                    try
                    {
                        tars::Int32 _ret;
                        _is.read(_ret, 0, true);

                        vector<tars::FileInfo> vf;
                        _is.read(vf, 2, true);
                        setResponseContext(msg->response.context);

                        callback_listFileInfo(_ret, vf);

                    }
                    catch(std::exception &ex)
                    {
                        callback_listFileInfo_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_listFileInfo_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    return tars::TARSSERVERSUCCESS;

                }
                case 2:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_preparePatchFile_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);
                    try
                    {
                        tars::Int32 _ret;
                        _is.read(_ret, 0, true);

                        setResponseContext(msg->response.context);

                        callback_preparePatchFile(_ret);

                    }
                    catch(std::exception &ex)
                    {
                        callback_preparePatchFile_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_preparePatchFile_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }

    protected:
        map<std::string, std::string> _mRspContext;
    };
    typedef tars::TC_AutoPtr<PatchCoroPrxCallback> PatchCoroPrxCallbackPtr;

    /* proxy for client */
    class PatchProxy : public tars::ServantProxy
    {
    public:
        typedef map<string, string> TARS_CONTEXT;
        tars::Int32 download(const std::string & file,tars::Int32 pos,vector<tars::Char> &vb,const map<string, string> &context = TARS_CONTEXT(),map<string, string> * pResponseContext = NULL)
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(file, 1);
            _os.write(pos, 2);
            _os.write(vb, 3);
            tars::ResponsePacket rep;
            std::map<string, string> _mStatus;
            tars_invoke(tars::TARSNORMAL,"download", _os.getByteBuffer(), context, _mStatus, rep);
            if(pResponseContext)
            {
                *pResponseContext = rep.context;
            }

            tars::TarsInputStream<tars::BufferReader> _is;
            _is.setBuffer(rep.sBuffer);
            tars::Int32 _ret;
            _is.read(_ret, 0, true);
            _is.read(vb, 3, true);
            return _ret;
        }

        void async_download(PatchPrxCallbackPtr callback,const std::string &file,tars::Int32 pos,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(file, 1);
            _os.write(pos, 2);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"download", _os.getByteBuffer(), context, _mStatus, callback);
        }
        
        promise::Future< PatchPrxCallbackPromise::PromisedownloadPtr > promise_async_download(const std::string &file,tars::Int32 pos,const map<string, string>& context)
        {
            promise::Promise< PatchPrxCallbackPromise::PromisedownloadPtr > promise;
            PatchPrxCallbackPromisePtr callback = new PatchPrxCallbackPromise(promise);

            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(file, 1);
            _os.write(pos, 2);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"download", _os.getByteBuffer(), context, _mStatus, callback);

            return promise.getFuture();
        }

        void coro_download(PatchCoroPrxCallbackPtr callback,const std::string &file,tars::Int32 pos,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(file, 1);
            _os.write(pos, 2);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"download", _os.getByteBuffer(), context, _mStatus, callback, true);
        }

        tars::Int32 listFileInfo(const std::string & path,vector<tars::FileInfo> &vf,const map<string, string> &context = TARS_CONTEXT(),map<string, string> * pResponseContext = NULL)
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(path, 1);
            _os.write(vf, 2);
            tars::ResponsePacket rep;
            std::map<string, string> _mStatus;
            tars_invoke(tars::TARSNORMAL,"listFileInfo", _os.getByteBuffer(), context, _mStatus, rep);
            if(pResponseContext)
            {
                *pResponseContext = rep.context;
            }

            tars::TarsInputStream<tars::BufferReader> _is;
            _is.setBuffer(rep.sBuffer);
            tars::Int32 _ret;
            _is.read(_ret, 0, true);
            _is.read(vf, 2, true);
            return _ret;
        }

        void async_listFileInfo(PatchPrxCallbackPtr callback,const std::string &path,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(path, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"listFileInfo", _os.getByteBuffer(), context, _mStatus, callback);
        }
        
        promise::Future< PatchPrxCallbackPromise::PromiselistFileInfoPtr > promise_async_listFileInfo(const std::string &path,const map<string, string>& context)
        {
            promise::Promise< PatchPrxCallbackPromise::PromiselistFileInfoPtr > promise;
            PatchPrxCallbackPromisePtr callback = new PatchPrxCallbackPromise(promise);

            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(path, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"listFileInfo", _os.getByteBuffer(), context, _mStatus, callback);

            return promise.getFuture();
        }

        void coro_listFileInfo(PatchCoroPrxCallbackPtr callback,const std::string &path,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(path, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"listFileInfo", _os.getByteBuffer(), context, _mStatus, callback, true);
        }

        tars::Int32 preparePatchFile(const std::string & app,const std::string & serverName,const std::string & patchFile,const map<string, string> &context = TARS_CONTEXT(),map<string, string> * pResponseContext = NULL)
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(app, 1);
            _os.write(serverName, 2);
            _os.write(patchFile, 3);
            tars::ResponsePacket rep;
            std::map<string, string> _mStatus;
            tars_invoke(tars::TARSNORMAL,"preparePatchFile", _os.getByteBuffer(), context, _mStatus, rep);
            if(pResponseContext)
            {
                *pResponseContext = rep.context;
            }

            tars::TarsInputStream<tars::BufferReader> _is;
            _is.setBuffer(rep.sBuffer);
            tars::Int32 _ret;
            _is.read(_ret, 0, true);
            return _ret;
        }

        void async_preparePatchFile(PatchPrxCallbackPtr callback,const std::string &app,const std::string &serverName,const std::string &patchFile,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(app, 1);
            _os.write(serverName, 2);
            _os.write(patchFile, 3);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"preparePatchFile", _os.getByteBuffer(), context, _mStatus, callback);
        }
        
        promise::Future< PatchPrxCallbackPromise::PromisepreparePatchFilePtr > promise_async_preparePatchFile(const std::string &app,const std::string &serverName,const std::string &patchFile,const map<string, string>& context)
        {
            promise::Promise< PatchPrxCallbackPromise::PromisepreparePatchFilePtr > promise;
            PatchPrxCallbackPromisePtr callback = new PatchPrxCallbackPromise(promise);

            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(app, 1);
            _os.write(serverName, 2);
            _os.write(patchFile, 3);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"preparePatchFile", _os.getByteBuffer(), context, _mStatus, callback);

            return promise.getFuture();
        }

        void coro_preparePatchFile(PatchCoroPrxCallbackPtr callback,const std::string &app,const std::string &serverName,const std::string &patchFile,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(app, 1);
            _os.write(serverName, 2);
            _os.write(patchFile, 3);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"preparePatchFile", _os.getByteBuffer(), context, _mStatus, callback, true);
        }

        PatchProxy* tars_hash(int64_t key)
        {
            return (PatchProxy*)ServantProxy::tars_hash(key);
        }

        PatchProxy* tars_consistent_hash(int64_t key)
        {
            return (PatchProxy*)ServantProxy::tars_consistent_hash(key);
        }

        PatchProxy* tars_set_timeout(int msecond)
        {
            return (PatchProxy*)ServantProxy::tars_set_timeout(msecond);
        }

    };
    typedef tars::TC_AutoPtr<PatchProxy> PatchPrx;

    /* servant for server */
    class Patch : public tars::Servant
    {
    public:
        virtual ~Patch(){}
        virtual tars::Int32 download(const std::string & file,tars::Int32 pos,vector<tars::Char> &vb,tars::TarsCurrentPtr current) = 0;
        static void async_response_download(tars::TarsCurrentPtr current, tars::Int32 _ret, const vector<tars::Char> &vb)
        {
            if (current->getRequestVersion() == TUPVERSION )
            {
                UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                tarsAttr.setVersion(current->getRequestVersion());
                tarsAttr.put("", _ret);
                tarsAttr.put("vb", vb);

                vector<char> sTupResponseBuffer;
                tarsAttr.encode(sTupResponseBuffer);
                current->sendResponse(tars::TARSSERVERSUCCESS, sTupResponseBuffer);
            }
            else
            {
                tars::TarsOutputStream<tars::BufferWriter> _os;
                _os.write(_ret, 0);

                _os.write(vb, 3);

                current->sendResponse(tars::TARSSERVERSUCCESS, _os.getByteBuffer());
            }
        }

        virtual tars::Int32 listFileInfo(const std::string & path,vector<tars::FileInfo> &vf,tars::TarsCurrentPtr current) = 0;
        static void async_response_listFileInfo(tars::TarsCurrentPtr current, tars::Int32 _ret, const vector<tars::FileInfo> &vf)
        {
            if (current->getRequestVersion() == TUPVERSION )
            {
                UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                tarsAttr.setVersion(current->getRequestVersion());
                tarsAttr.put("", _ret);
                tarsAttr.put("vf", vf);

                vector<char> sTupResponseBuffer;
                tarsAttr.encode(sTupResponseBuffer);
                current->sendResponse(tars::TARSSERVERSUCCESS, sTupResponseBuffer);
            }
            else
            {
                tars::TarsOutputStream<tars::BufferWriter> _os;
                _os.write(_ret, 0);

                _os.write(vf, 2);

                current->sendResponse(tars::TARSSERVERSUCCESS, _os.getByteBuffer());
            }
        }

        virtual tars::Int32 preparePatchFile(const std::string & app,const std::string & serverName,const std::string & patchFile,tars::TarsCurrentPtr current) = 0;
        static void async_response_preparePatchFile(tars::TarsCurrentPtr current, tars::Int32 _ret)
        {
            if (current->getRequestVersion() == TUPVERSION )
            {
                UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                tarsAttr.setVersion(current->getRequestVersion());
                tarsAttr.put("", _ret);

                vector<char> sTupResponseBuffer;
                tarsAttr.encode(sTupResponseBuffer);
                current->sendResponse(tars::TARSSERVERSUCCESS, sTupResponseBuffer);
            }
            else
            {
                tars::TarsOutputStream<tars::BufferWriter> _os;
                _os.write(_ret, 0);

                current->sendResponse(tars::TARSSERVERSUCCESS, _os.getByteBuffer());
            }
        }

    public:
        int onDispatch(tars::TarsCurrentPtr _current, vector<char> &_sResponseBuffer)
        {
            static ::std::string __tars__Patch_all[]=
            {
                "download",
                "listFileInfo",
                "preparePatchFile"
            };

            pair<string*, string*> r = equal_range(__tars__Patch_all, __tars__Patch_all+3, _current->getFuncName());
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __tars__Patch_all)
            {
                case 0:
                {
                    tars::TarsInputStream<tars::BufferReader> _is;
                    _is.setBuffer(_current->getRequestBuffer());
                    std::string file;
                    tars::Int32 pos;
                    vector<tars::Char> vb;
                    if (_current->getRequestVersion() == TUPVERSION)
                    {
                        UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                        tarsAttr.setVersion(_current->getRequestVersion());
                        tarsAttr.decode(_current->getRequestBuffer());
                        tarsAttr.get("file", file);
                        tarsAttr.get("pos", pos);
                        tarsAttr.getByDefault("vb", vb, vb);
                    }
                    else
                    {
                        _is.read(file, 1, true);
                        _is.read(pos, 2, true);
                        _is.read(vb, 3, false);
                    }
                    tars::Int32 _ret = download(file,pos,vb, _current);
                    if(_current->isResponse())
                    {
                        if (_current->getRequestVersion() == TUPVERSION )
                        {
                            UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                            tarsAttr.setVersion(_current->getRequestVersion());
                            tarsAttr.put("", _ret);
                            tarsAttr.put("vb", vb);
                            tarsAttr.encode(_sResponseBuffer);
                        }
                        else
                        {
                            tars::TarsOutputStream<tars::BufferWriter> _os;
                            _os.write(_ret, 0);
                            _os.write(vb, 3);
                            _os.swap(_sResponseBuffer);
                        }
                    }
                    return tars::TARSSERVERSUCCESS;

                }
                case 1:
                {
                    tars::TarsInputStream<tars::BufferReader> _is;
                    _is.setBuffer(_current->getRequestBuffer());
                    std::string path;
                    vector<tars::FileInfo> vf;
                    if (_current->getRequestVersion() == TUPVERSION)
                    {
                        UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                        tarsAttr.setVersion(_current->getRequestVersion());
                        tarsAttr.decode(_current->getRequestBuffer());
                        tarsAttr.get("path", path);
                        tarsAttr.getByDefault("vf", vf, vf);
                    }
                    else
                    {
                        _is.read(path, 1, true);
                        _is.read(vf, 2, false);
                    }
                    tars::Int32 _ret = listFileInfo(path,vf, _current);
                    if(_current->isResponse())
                    {
                        if (_current->getRequestVersion() == TUPVERSION )
                        {
                            UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                            tarsAttr.setVersion(_current->getRequestVersion());
                            tarsAttr.put("", _ret);
                            tarsAttr.put("vf", vf);
                            tarsAttr.encode(_sResponseBuffer);
                        }
                        else
                        {
                            tars::TarsOutputStream<tars::BufferWriter> _os;
                            _os.write(_ret, 0);
                            _os.write(vf, 2);
                            _os.swap(_sResponseBuffer);
                        }
                    }
                    return tars::TARSSERVERSUCCESS;

                }
                case 2:
                {
                    tars::TarsInputStream<tars::BufferReader> _is;
                    _is.setBuffer(_current->getRequestBuffer());
                    std::string app;
                    std::string serverName;
                    std::string patchFile;
                    if (_current->getRequestVersion() == TUPVERSION)
                    {
                        UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                        tarsAttr.setVersion(_current->getRequestVersion());
                        tarsAttr.decode(_current->getRequestBuffer());
                        tarsAttr.get("app", app);
                        tarsAttr.get("serverName", serverName);
                        tarsAttr.get("patchFile", patchFile);
                    }
                    else
                    {
                        _is.read(app, 1, true);
                        _is.read(serverName, 2, true);
                        _is.read(patchFile, 3, true);
                    }
                    tars::Int32 _ret = preparePatchFile(app,serverName,patchFile, _current);
                    if(_current->isResponse())
                    {
                        if (_current->getRequestVersion() == TUPVERSION )
                        {
                            UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                            tarsAttr.setVersion(_current->getRequestVersion());
                            tarsAttr.put("", _ret);
                            tarsAttr.encode(_sResponseBuffer);
                        }
                        else
                        {
                            tars::TarsOutputStream<tars::BufferWriter> _os;
                            _os.write(_ret, 0);
                            _os.swap(_sResponseBuffer);
                        }
                    }
                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }
    };


}



#endif
